# Generated by Django 4.2.23 on 2025-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(default='jecinta Muhia', max_length=100),
            preserve_default=False,
        ),
    ]
