# Generated by Django 4.2.23 on 2025-06-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='full_name',
        ),
    ]
