# Generated by Django 5.2.3 on 2025-06-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplierid',
        ),
    ]
