# Generated by Django 5.2.3 on 2025-06-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderItems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('order_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderItems.orderitems')),
            ],
        ),
    ]
